// <auto-generated />
namespace entitieshrms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class hrmsinit2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hrmsinit2));
        
        string IMigrationMetadata.Id
        {
            get { return "202007210732113_hrmsinit2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
